<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Booking</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 40px;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .header img {
            max-height: 60px;
        }

        .title {
            font-size: 20px;
            margin-top: 10px;
            color: #4A575A;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        td {
            padding: 10px;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background-color: #f4f4f4;
        }

        .label {
            font-weight: 400;
            font-style: normal;
            font-size: 17px;
            color: #4A575A;
        }

        .value {
            width: 70%;
        }

        .footer {
            position: absolute;
            bottom: 40px;
            left: 40px;
            right: 40px;
            text-align: center;
            font-size: 12px;
            color: #888;
        }

        .sacramento-regular1 {
            font-family: "Sacramento", cursive;
            font-weight: 400;
            font-style: normal;
            font-size: 15px;
            color: #4A575A;
        }

        .sacramento-regular2 {
            font-family: "Sacramento", cursive;
            font-weight: 400;
            font-style: normal;
            font-size: 15px;
            color: #7E84F2;
        }

        .sacramento-regular1,
        .sacramento-regular2 {
            display: inline;
        }
    </style>
</head>

<body>

    <div class="header">
        {{-- Logo --}}
        <img src="{{ public_path('images/logo/logo-bungalow2.png') }}" alt="Logo" style="max-height: 60px;">
        <div>
            <h1 class="sacramento-regular1">My</h1>
            <h1 class="sacramento-regular2">Bungalow</h1>
        </div>

        <div class="title">Booking Details</div>
    </div>

    <table>
        <tr>
            <td class="label">Booking id:</td>
            <td class="value">{{ $locacao->id }}</td>
        </tr>
        <tr>
            <td class="label">Client:</td>
            <td class="value">{{ $locacao->user->name }}</td>
        </tr>
        <tr>
            <td class="label">e-mail:</td>
            <td class="value">{{ $locacao->user->email }}</td>
        </tr>
        <tr>
            <td class="label">Location:</td>
            <td class="value">{{ $locacao->bungalow->modelo }}</td>
        </tr>
        <tr>
            <td class="label">Check-in:</td>
            <td class="value">{{ \Carbon\Carbon::parse($locacao->data_inicio)->format('d-m-Y') }}</td>
        </tr>
        <tr>
            <td class="label">Check-out:</td>
            <td class="value"> {{ \Carbon\Carbon::parse($locacao->data_fim)->format('d-m-Y') }}</td>
        </tr>
    </table>

    <div class="footer">
        Automatically generated by {{ config('app.name') }} on {{ now()->format('d/m/Y H:i') }}
    </div>

</body>

</html>
